import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import "./globals.css";
import BackToTop from "../components/BackToTop";

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${archivo.variable} antialiased`}
      >
        {children}
        <BackToTop />
      </body>
    </html>
  );
}
