// app/layout.tsx
import "./globals.css";
import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import BackToTop from "../components/BackToTop";
import { getSiteSettings } from "@/app/api/get-site-settings";
import { Providers } from '@/app/providers';

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gold Star",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const settings = await getSiteSettings();

  return (
    <html lang="en">
      <body className={`${archivo.variable} antialiased bg-white text-gray-900`}>
        <Providers initialSettings={settings}>
          {children}
          <BackToTop />
        </Providers>
      </body>
    </html>
  );
}
